<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b83a4a1-79b5-4985-8dc8-08b6391f4a64</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Borrowing\Borrowing.Controllers\Borrowing.Controllers.csproj" />
    <ProjectReference Include="..\Borrowing\LibraryManagement.Application\Borrowing.Application.csproj" />
    <ProjectReference Include="..\Borrowing\LibraryManagement.Infrastructure\Borrowing.Infrastructure.csproj" />
    <ProjectReference Include="..\Identity\Identity.Application\Identity.Application.csproj" />
    <ProjectReference Include="..\Identity\Identity.Controllers\Identity.Controllers.csproj" />
    <ProjectReference Include="..\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\LibraryManagement.Contracts\LibraryManagement.Contracts.csproj" />
  </ItemGroup>

</Project>
